import os, datetime, glob
from posixpath import splitext


# getting file length
max_repsize = 9
lines_unit = 10
def get_file_profile(fname):
    with open(fname) as f:
        for i, l in enumerate(f):
            pass
    i += 1
    return min(int(i / lines_unit), max_repsize) 

# Get Base file dir
logs_dir = os.path.dirname(os.path.dirname(__file__))

# Date and times:
now = datetime.datetime.now()
filename = now.strftime("%Y_%m_%d") + "_cl.md"
date_str = now.strftime("%Y.%m.%d")
time_str = now.strftime("%H:%M:%S")
file_dir = os.path.join(logs_dir, filename)

# User Name:
admin = "Junru Tao"

str_data = """# :hammer: ChangeLogs
> _Lastest Update on ChangeLogs:_<br>
> __Date stamp: {0}__<br>
> __Time stamp: {1}__<br>
> __Author: {2}__
---
""".format(date_str, time_str, admin)

changlog_file = ""
log_files = []

for infile in glob.glob(os.path.join(logs_dir, "*.md")):
    if "ChangeLog.md" in infile:
        changlog_file = infile
    else:
        log_files.append(infile)

if not changlog_file:
    raise FileNotFoundError("can not find the \"ChangeFile.md\" File")

split_at = 6
counter = 0

#  this will be appended to represent the length of the change log.
length_rep_symble = ":bread:"

str_data += "\n<div align=right>\n\n\
( _Note:_ \"%s\" _represent %d lines_ )\n\n</div> \n\n" % (length_rep_symble, lines_unit)

for f in log_files:
    counter += 1
    len = get_file_profile(f)
    title =  os.path.basename(os.path.splitext(f)[0])
    title = str(title).replace("_", "/")
    title = "Change_Log - Date:" + title[:-3]
    file = "./" + os.path.basename(f)
    str_data += "\n :bookmark_tabs: _{2:03d}_. [{0}]({1}) : ".format(title, file, counter)
    
    for i in range(len):
        str_data += length_rep_symble
        
    str_data += "\n"
    
    # give the text a bit of spacing: 
    if (counter % split_at) == 0:
        str_data += "\n\n"
    
str_data += "\n\n\n<br><br>\n\n> This `Markdown` File is generated by a changLog bot.\
 Please do not change anything in this file. The bot will rewrite this file everytime."
str_data += "\n\n--------\n\n"
# print(str_data)
if changlog_file:
    with open(changlog_file, "w") as file:
        file.write(str_data)
        
print(changlog_file)  
exit(0)